package com.scivicslab.htmlsaurus;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.*;
import java.util.regex.Pattern;

/**
 * Builds and reorders the site navigation tree from a Docusaurus-compatible docs directory.
 *
 * <p>Handles Docusaurus conventions: numeric prefixes for ordering,
 * {@code _category_.json} for category labels, same-name Markdown files as category index pages,
 * and {@code docusaurus.config.ts/js} + {@code sidebars.ts/js} for navbar ordering.
 */
class NavTreeBuilder {

    /** Matches numeric prefix patterns like {@code 01_getting-started}. */
    private static final Pattern NUM_PREFIX           = Pattern.compile("^(\\d+)_(.*)$");
    /** Matches {@code "label": "..."} in {@code _category_.json}. */
    private static final Pattern CATEGORY_LABEL_PAT   = Pattern.compile("\"label\"\\s*:\\s*\"([^\"]+)\"");
    /** Matches {@code dirName: '...'} in sidebars config. */
    private static final Pattern SIDEBAR_DIR_NAME_PAT = Pattern.compile("dirName:\\s*['\"]([^'\"]+)['\"]");
    /** Matches a top-level sidebar key followed by {@code [}. */
    private static final Pattern SIDEBAR_KEY_PAT      = Pattern.compile("(\\w+):\\s*\\[");
    /** Matches a sidebarId-based navbar item with its label (DOTALL). */
    private static final Pattern SIDEBAR_ITEM_PAT     = Pattern.compile(
        "sidebarId:\\s*['\"]([^'\"]+)['\"].*?label:\\s*['\"]([^'\"]+)['\"]", Pattern.DOTALL);
    /** Matches a docId-based navbar item with its label (DOTALL). */
    private static final Pattern DOC_ITEM_PAT         = Pattern.compile(
        "docId:\\s*['\"]([^'\"]+)['\"].*?label:\\s*['\"]([^'\"]+)['\"]", Pattern.DOTALL);

    /** Matches {@code "item.label.<original>": { "message": "<translated>" }} in navbar.json. */
    private static final Pattern NAVBAR_LABEL_PAT = Pattern.compile(
        "\"item\\.label\\.([^\"]+)\":\\s*\\{\\s*\"message\":\\s*\"([^\"]+)\"");

    private final Path docsDir;
    private final Path projectRoot;
    private final boolean production;
    private final MarkdownConverter converter;
    private final String currentLocale;
    private final String defaultLocale;

    /**
     * @param docsDir       source directory containing Markdown files
     * @param production    {@code true} to generate production-style directory URLs
     * @param converter     Markdown converter used for frontmatter extraction during tree building
     * @param currentLocale locale code of this build (e.g., "en"), or null for default
     * @param defaultLocale default locale from docusaurus.config (e.g., "ja"), or null
     */
    NavTreeBuilder(Path docsDir, boolean production, MarkdownConverter converter,
                   String currentLocale, String defaultLocale) {
        this.docsDir = docsDir;
        this.projectRoot = findProjectRoot(docsDir);
        this.production = production;
        this.converter = converter;
        this.currentLocale = currentLocale;
        this.defaultLocale = defaultLocale;
    }

    /**
     * Walks up from docsDir to find the Docusaurus project root — the nearest ancestor
     * containing a {@code docs/} subdirectory. Handles alternate-locale builds where
     * docsDir is deep inside {@code i18n/<locale>/docusaurus-plugin-content-docs/current}.
     */
    private static Path findProjectRoot(Path docsDir) {
        Path p = docsDir.getParent();
        while (p != null) {
            if (Files.isDirectory(p.resolve("docs"))) return p;
            p = p.getParent();
        }
        return docsDir.getParent();
    }

    /**
     * Builds and reorders the navigation tree: scans {@code docsDir} then applies ordering
     * from {@code docusaurus.config.ts/js}.
     *
     * @return the root {@link SiteNode} representing the entire site
     * @throws IOException if file I/O fails
     */
    SiteNode build() throws IOException {
        return reorderFromDocusaurusConfig(buildTree(docsDir));
    }

    /**
     * Reorders top-level navbar sections according to the order defined in
     * {@code docusaurus.config.ts} (or {@code .js}). Falls back to the original
     * order when the config files are absent or unparseable.
     */
    private SiteNode reorderFromDocusaurusConfig(SiteNode root) {
        Path configFile = resolveFirst(projectRoot, "docusaurus.config.ts", "docusaurus.config.js");
        Path sidebarsFile = resolveFirst(projectRoot, "sidebars.ts", "sidebars.js");
        if (configFile == null || sidebarsFile == null) return root;

        try {
            String configContent = Files.readString(configFile);
            String sidebarsContent = Files.readString(sidebarsFile);

            // Extract sidebarId -> dirName from sidebars.
            // Find each autogenerated dirName and locate the nearest preceding sidebar key.
            Map<String, String> sidebarIdToDirName = new HashMap<>();
            var dnMatcher = SIDEBAR_DIR_NAME_PAT.matcher(sidebarsContent);
            while (dnMatcher.find()) {
                String preceding = sidebarsContent.substring(0, dnMatcher.start());
                var km = SIDEBAR_KEY_PAT.matcher(preceding);
                String lastKey = null;
                while (km.find()) lastKey = km.group(1);
                if (lastKey != null && !sidebarIdToDirName.containsKey(lastKey)) {
                    sidebarIdToDirName.put(lastKey, dnMatcher.group(1));
                }
            }

            // Collect navbar items (sidebarId-based and docId-based) with their position in config.
            record NavItem(int pos, String dirName, String label) {}
            List<NavItem> navItems = new ArrayList<>();

            var m1 = SIDEBAR_ITEM_PAT.matcher(configContent);
            while (m1.find()) {
                String dir = sidebarIdToDirName.get(m1.group(1));
                if (dir != null) navItems.add(new NavItem(m1.start(), dir, m1.group(2)));
            }

            var m2 = DOC_ITEM_PAT.matcher(configContent);
            while (m2.find()) {
                String dir = m2.group(1).split("/")[0];
                if (!dir.isEmpty()) navItems.add(new NavItem(m2.start(), dir, m2.group(2)));
            }

            navItems.sort(Comparator.comparingInt(NavItem::pos));

            // Build ordered dirName list with labels (deduplicated)
            List<String> orderedDirNames = new ArrayList<>();
            Map<String, String> dirNameToLabel = new HashMap<>();
            for (NavItem item : navItems) {
                if (!orderedDirNames.contains(item.dirName())) {
                    orderedDirNames.add(item.dirName());
                    dirNameToLabel.put(item.dirName(), item.label());
                }
            }
            if (orderedDirNames.isEmpty()) return root;

            // Map children by directory name (first path segment of href)
            Map<String, SiteNode> childByDirName = new LinkedHashMap<>();
            List<SiteNode> unmatchedChildren = new ArrayList<>();
            for (SiteNode child : root.children()) {
                String dirName = SiteBuilder.dirNameForSection(child);
                if (!dirName.isEmpty()) {
                    childByDirName.put(dirName, child);
                } else {
                    unmatchedChildren.add(child);
                }
            }

            // Load translated navbar labels from i18n/<locale>/docusaurus-theme-classic/navbar.json.
            // Applied for all locales: default locale configs often use English labels in
            // docusaurus.config.ts while the actual display labels live in navbar.json.
            if (currentLocale != null) {
                Path navbarJson = projectRoot.resolve(
                    "i18n/" + currentLocale + "/docusaurus-theme-classic/navbar.json");
                if (Files.exists(navbarJson)) {
                    try {
                        String navbarContent = Files.readString(navbarJson);
                        var nm = NAVBAR_LABEL_PAT.matcher(navbarContent);
                        while (nm.find()) {
                            String originalLabel = nm.group(1);
                            String translatedLabel = nm.group(2);
                            // Find which dirName has this original label and update it
                            for (String dirName : orderedDirNames) {
                                if (originalLabel.equals(dirNameToLabel.get(dirName))) {
                                    dirNameToLabel.put(dirName, translatedLabel);
                                }
                            }
                        }
                    } catch (IOException ignored) {}
                }
            }

            // Reorder and apply labels from docusaurus config
            List<SiteNode> reordered = new ArrayList<>();
            for (String dirName : orderedDirNames) {
                SiteNode child = childByDirName.remove(dirName);
                if (child != null) {
                    String newLabel = dirNameToLabel.get(dirName);
                    if (newLabel != null && !newLabel.equals(child.label())) {
                        child = new SiteNode(newLabel, child.href(), child.isDir(), child.children(), child.catLink());
                    }
                    reordered.add(child);
                }
            }
            reordered.addAll(childByDirName.values()); // remaining not in config
            reordered.addAll(unmatchedChildren);

            return new SiteNode(root.label(), root.href(), root.isDir(), reordered, root.catLink());
        } catch (IOException e) {
            return root;
        }
    }

    /** Returns the first existing file from the given candidates, or {@code null}. */
    private static Path resolveFirst(Path dir, String... names) {
        for (String name : names) {
            Path p = dir.resolve(name);
            if (Files.exists(p)) return p;
        }
        return null;
    }

    /**
     * Recursively builds the navigation tree from the docs directory structure.
     * Handles Docusaurus conventions: numeric prefixes for ordering, {@code _category_.json}
     * for category labels, and same-name Markdown files as category index pages.
     *
     * @param dir the directory to scan
     * @return root {@link SiteNode} representing the directory
     * @throws IOException if file I/O fails
     */
    private SiteNode buildTree(Path dir) throws IOException {
        List<Path> entries;
        try (var stream = Files.list(dir)) {
            entries = stream.sorted(Comparator.comparing(p -> sortKey(p.getFileName().toString()))).toList();
        }

        String dirBase = SiteBuilder.stripNumericPrefix(dir.getFileName().toString());
        List<Path> mdFiles = entries.stream()
            .filter(e -> !Files.isDirectory(e) && e.toString().endsWith(".md"))
            .toList();
        boolean hasSubdirs = entries.stream().anyMatch(Files::isDirectory);

        // Find a same-name .md file if it exists
        Path sameNameMd = null;
        for (Path md : mdFiles) {
            String mdBase = SiteBuilder.stripNumericPrefix(SiteBuilder.stripExtension(md.getFileName().toString()));
            if (dirBase.equals(mdBase)) {
                sameNameMd = md;
                break;
            }
        }

        // Docusaurus convention: if the directory contains ONLY a same-name .md file
        // (no subdirs, no other .md files), treat it as a direct leaf page link.
        // URL is based on the directory path (not the file path), matching Docusaurus behavior.
        if (sameNameMd != null && !hasSubdirs && mdFiles.size() == 1) {
            String[] fm = converter.parseFrontmatter(Files.readString(sameNameMd));
            String title = fm[0].isBlank() ? dirBase : fm[0];
            String fmId = fm[2];
            Path dirRel = docsDir.relativize(dir);
            String href;
            if (!fmId.isEmpty()) {
                // id overrides the last directory segment (same-name pattern)
                String parentPath = dirRel.getParent() == null ? "" : dirRel.getParent().toString().replace('\\', '/');
                String parentClean = parentPath.isEmpty() ? "" : SiteBuilder.cleanRelPath(parentPath) + "/";
                href = "/" + parentClean + fmId + (production ? "/" : ".html");
            } else {
                href = "/" + SiteBuilder.cleanRelPath(dirRel.toString().replace('\\', '/')) + (production ? "/" : ".html");
            }
            return new SiteNode(title, href, false, List.of(), null);
        }

        // Build category. If there's a same-name .md (Pattern 2: same-name .md + subdirs),
        // use it as the category label source and make the category header a clickable link.
        // The same-name .md is NOT added as a child item (Docusaurus convention).
        String label;
        String catHref = null;
        List<SiteNode> children = new ArrayList<>();
        if (sameNameMd != null) {
            String[] fm = converter.parseFrontmatter(Files.readString(sameNameMd));
            label = fm[0].isBlank() ? dirBase : fm[0];
            String fmId = fm[2];
            // Category header links to the directory URL (same rule as Pattern 1)
            Path dirRel = docsDir.relativize(dir);
            if (!fmId.isEmpty()) {
                String parentPath = dirRel.getParent() == null ? "" : dirRel.getParent().toString().replace('\\', '/');
                String parentClean = parentPath.isEmpty() ? "" : SiteBuilder.cleanRelPath(parentPath) + "/";
                catHref = "/" + parentClean + fmId + (production ? "/" : ".html");
            } else {
                catHref = "/" + SiteBuilder.cleanRelPath(dirRel.toString().replace('\\', '/')) + (production ? "/" : ".html");
            }
        } else {
            label = readCategoryLabel(dir);
        }

        for (Path entry : entries) {
            if (entry.equals(sameNameMd)) continue; // not shown as child (Docusaurus convention)
            if (Files.isDirectory(entry)) {
                children.add(buildTree(entry));
            } else if (entry.toString().endsWith(".md")) {
                String[] fm = converter.parseFrontmatter(Files.readString(entry));
                String title = fm[0].isBlank()
                    ? SiteBuilder.stripNumericPrefix(SiteBuilder.stripExtension(entry.getFileName().toString())) : fm[0];
                String fmId = fm[2];
                Path rel = docsDir.relativize(entry);
                String href;
                if (!fmId.isEmpty()) {
                    String parentPath = rel.getParent() == null ? "" : rel.getParent().toString().replace('\\', '/');
                    String parentClean = parentPath.isEmpty() ? "" : SiteBuilder.cleanRelPath(parentPath) + "/";
                    href = "/" + parentClean + fmId + (production ? "/" : ".html");
                } else {
                    href = "/" + SiteBuilder.cleanRelPath(rel.toString().replace('\\', '/').replaceAll("\\.md$", "")) + (production ? "/" : ".html");
                }
                children.add(new SiteNode(title, href, false, List.of(), null));
            }
        }

        // href is always the navigation target (for navbar and index.html redirect);
        // catLink is non-null only for Pattern 2, used by renderSidebar for the clickable header
        String navHref = catHref != null ? catHref : firstHref(children);
        return new SiteNode(label, navHref, true, children, catHref);
    }

    /**
     * Finds the href of the first leaf page in a subtree (depth-first).
     * Used to determine the landing page for category nodes.
     */
    private String firstHref(List<SiteNode> nodes) {
        for (SiteNode n : nodes) {
            if (!n.isDir()) return n.href();
            String h = firstHref(n.children());
            if (h != null) return h;
        }
        return null;
    }

    /** Generates a zero-padded sort key from a numeric prefix (e.g., {@code 3_foo} → {@code 0000000003_foo}). */
    private String sortKey(String name) {
        var m = NUM_PREFIX.matcher(name);
        if (m.matches()) return String.format("%010d_%s", Long.parseLong(m.group(1)), m.group(2));
        return name;
    }

    /**
     * Reads a category label from a Docusaurus {@code _category_.json} file,
     * falling back to the directory name with its numeric prefix stripped.
     */
    private String readCategoryLabel(Path dir) {
        Path cat = dir.resolve("_category_.json");
        if (Files.exists(cat)) {
            try {
                String json = Files.readString(cat);
                var m = CATEGORY_LABEL_PAT.matcher(json);
                if (m.find()) return m.group(1);
            } catch (IOException ignored) {}
        }
        return SiteBuilder.stripNumericPrefix(dir.getFileName().toString());
    }

}
